Fixed 'pip install cheroot' on Python 2
On Python 2 "pip install cheroot" ends with error:
ERROR: more-itertools requires Python '>=3.4' but the running Python is 2.7.15

The reason: more_itertools package from version 6 does not support Python 2.