Allow HTTPServer.tick error under py2 @ test_conn
This exception is being triggered by the underlying socket closing
logic under Python 2:

    Traceback (most recent call last):
      File "cheroot/server.py", line 1798, in serve
        self.tick()
      File "cheroot/server.py", line 2038, in tick
        conn = self._connections.get_conn()
      File "cheroot/connections.py", line 142, in get_conn
        for _, key in self._selector.get_map().items():
      File "cheroot/test/test_conn.py", line 1106, in __call__
        conn.close()
      File "cheroot/server.py", line 1356, in close
        self._close_kernel_socket()
      File "cheroot/server.py", line 1479, in _close_kernel_socket
        self.socket._sock.close()
      File "<...>/lib/python2.7/socket.py", line 174, in _dummy
        raise error(EBADF, 'Bad file descriptor')
    error: [Errno 9] Bad file descriptor

This patch tells tests to ignore it because it's triggered by the
way `test_invalid_selected_connection` corrupts the socket.