Update to latest (#1)
* Use the newly included _compat.suppress function
to make it python2 compatible using a EAFP style,
instead of using `inspect.isclass`.

* Include feedback re: the test_cli.py structure.

 - Unify the bind_addr test into a single function
   parametrized by pytest.

 - Add additional parameters in the `test_parse_wsgi_bind_addr`
   function to further test some additional cases.

 - Encapsulate the WSGI mock definition, patching,
   and injection in the test using pytest conventions.

* 📝 Add Tidelift subscription mention into README

* 📝 Upgrade the copyright year in license

* 📝 Replace GitHub emoji shortcuts w/ real emojis 🙋

* 📝 Add Tidelift badge to README

* Upgrade deprecated version arg in Python action

* Add Tidelift to known words for spellcheck

* Use new `--no-testmon` option in pytest

Before testmon v1.0.0 it was called `--testmon-off`.

* Stop ignoring `cheroot.ssl.pyopenssl` in pytest

* Downgrade minimum testmon to v1.0.0

* Limit pytest-testmon below v1.0.0

* Drop fallback for pyopenssl debug in gh actions

* Add another "connection aborted" str to test_ssl

* Bump xcode in Circle CI to v9.3.1

* Bump xcode in Circle CI to v11.3.0

* Set xcode to v11.2.1 in Circle CI

* Revert "Set xcode to v11.2.1 in Circle CI"

This reverts commit bb9e0f5b57a0fe373a213e0bba43375a79421c4c.

* Revert "Revert "Set xcode to v11.2.1 in Circle CI""

This reverts commit de121de0602f4697eba87ae2911b6a67cbbb702a.

* Drop win2016 from nonfallback condition @ test_ssl

* Don't cancel other jobs on fail in GH Actions

* Extend expected TLS errors on Linux @ GH Actions

* Revert "Drop win2016 from nonfallback condition @ test_ssl"

This reverts commit b2983e50414d56ffe5d9dd0a379a7276a06aac6d.

* Use "latest" VM identifiers in GH Actions

* Add more linter jobs to GitHub Actions CI/CD

* Make Tidelift button link lowercase

* Adjust fallback conditions for win2016 @ gh-action

* modified 3/5 files to conform to flake8 WPS336 style, removing explicit string concat

* finished up the other two files, removed explicit string concatenation

* finished up the other two files, removed explicit string concatenation

* addressing 3 long lines identified by codeclimate

* addressed tox test failures, where name 'b' was not defined

* PEP-8 style issue, continuation line was under-indented for visual indent

* respond to feedback, use string interpolation

* encode both operands in ascii rather than b''

* string interpolation where possible for appending strings

* string interpolation where possible and fix indent with .format... method call

* two instances where lines are too long

* two redundant backslashes

* backslash needed for line continuation

* flake8 rules around hanging and visual indents

* flake8 rules around hanging and visual indents

* codeclimate - unaligned for hanging indent

* flake8 fixing over indentation

* flake8 fixing over indentation

* Populate more PEP 3333 SSL environment [Built-in]

* Add SSL_TLS_SNI environment var [Built-in]

* Add server SSL environment vars [Built-in]

* Add alternate certificate parsing method [Built-in]

* Add SSL version to environment [pyOpenSSL]

* Add SSL environment tests

* fix name of `env_cert_dict`

Co-Authored-By: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* 🎨Address str format conserns in `cheroot.server`

* 🎨 Use placeholder names in threadpool str format

* 🎨 Use `bytes.join()` in `cheroot.test.test_conn`

* 🎨Use named str.format placeholders @ `test_ssl`

* 🎨Use named str fmt placeholders @ `cheroot.wsgi`

* 📝 Explicitly set junit_family in pytest config

* ⇪ Set min pytest version to 4.6.6

* 📝🎨 Explain pytest args in the config

* 🎨 Order options aplhabetically in pytest config

* 🎨 Multiline norecursedirs pytest arg in config

* Add setuptools_scm_git_archive to pyproject.toml

* Explicitly install wheel into tox testenv

* Upgrade pip in tox env

* 🔥 Exclude broken colorama from deps under Py 3.4

* Drop unnecessary pre-commit exclusions

* Add a trailing comma to pyproject.toml requires

* Add initial Flake8 config

Ref #253

* Add flakehell to failing CI checks

* Integrate `--show-diff-on-failure` in `pre-commit`

* 📝Restrict issues interface to existing templates

* Add emojis to contact_links config

* Upgrade issue template with labels

* Integrate flake8-pytest-style into pre-commit conf

* Add flake8-pytest-style & flake8-2020 to flakehell

* Add a YAML Lint config

* Use explicit document marker in YAML

* Bump add-trailing-comma hook ver in pre-commit

* Integrate RST linter into pre-commit

* Switch pydocstyle to the official PyCQA/pydocstyle

* Relocate remove-tabs hook to the top

* Rearrange pre-commit hooks to modify first

* Fix rst linter file regex in pre-commit config

* Upgrade virtualenv in Travis CI

* Update GH Actions Workflows badges in README

* Bump license © year to 2020

* 📝 Add change notes for v8.3.0

* Add TLS to the list of known words

* 🐛 Don't check docs/ and CHANGES with rst-linker

* 🐛 Fix PT006 flake8 rule violation in `test_ssl`

* Enable cache in GH Actions Workflows

* 🚑 Fix syntax error in GH Actions Workflows

* 📝 Turn enterprise section in README into a table

* Fix cache keys in GH Actions

* Update codecov from 2.0.15 to 2.0.16

* Added empty Zuul config

* zuul: Add basic tox jobs

This commits adds the basic tox jobs which do much of the linting
for the project.

* Ignore GH Actions Workflows badge URL

Originally I thought it's
https://github.com/ansible/ansible/pull/66646/files#diff-76be13d257cf5c18b30c66364445527fR94
but turned out it's about Accept header, not User-Agent:
https://github.com/sphinx-doc/sphinx/issues/7247

* Update coverage from 4.5.3 to 5.0.4

* Update codecov from 2.0.16 to 2.0.22

* Use match in pytest.raises to address PT011

* Adjust PT001 flake8-pytest-style violation setting

https://github.com/m-burst/flake8-pytest-style/issues/4

* Set PT006 flake8-pytest-style setting explicitly

* Configure PT007 flake8-pytest-style check

https://github.com/m-burst/flake8-pytest-style/issues/2

* Add different py versions testing for Zuul

This patch adds py27, py35, py36, py37 and py38 testing by zuul.

* Specify min versions of extra flake8 plugins

* Temporary limit pytest<5.4

Refs:
* https://github.com/Teemu/pytest-sugar/pull/188
* https://github.com/pytest-dev/pytest/issues/6931

* Pin last coverage supported by Python 3.4

* Pin pytest-testmon. Ref #279.

* Temporary limit pytest<5.4

Refs:
* https://github.com/Teemu/pytest-sugar/pull/188
* https://github.com/pytest-dev/pytest/issues/6931

* Add fixture for simple WSGI server. Ref #263.

* Stop the server when done.

* Following guidance in docs, use prepare/serve instead of start.

* Move 'run in thread' functionality into HTTPServer, but protect for internal use (for now).

* Use new `--no-testmon` option in pytest

Before testmon v1.0.0 it was called `--testmon-off`.

* Bump setuptools in tox's testenv

This should prevent DeprecationWarnings
about imports from collections.

* Remove nightly from tests. Ref #279.

* Patch URI validation in tests under Python 3.8+

* Revert "Remove nightly from tests. Ref #279."

This reverts commit bd485c5e6b5aec4842f69f15ff1c7dd666c75e7b.

* Patch URI validation in tests under Python 3.8+

* Limit pytest-testmon below v1.0.0

* Upgrade virtualenv in Travis CI

* Explicitly install wheel into tox testenv

* Upgrade pip in tox env

* Restrict colorama below v0.4.2 under Python 3.4

* Fixture should provide a URL to the server.

* Add test capturing failure. Ref #263.

* Add concurrent futures backport for Python 2.7 compatibilty.

* Extract separate fixture for unix file sock

* Extract another fixture for the URL validation monkeypatch

* Remove fixture, undocumented and presumed unneeded.

* Use canonical form of null character.

* Use canonical form of null character.

* Prefer using 'urllib.parse.quote' to manual substitution.

* Copy pasta

* Remove client from peercreds tests. Fixes #276.

* Update coverage from 5.0.4 to 5.1

* Make pytest fail on flaky xfail (xpass)

* Unxfail test_large_request

Ref: #106

* Add Tidelift to project URLs in metadata

Ref:
https://tidelift.com/subscription/pkg/pypi-cheroot?utm_source=pypi-cheroot&utm_medium=referral&utm_campaign=pypi

* Check for ResourceWarnings while testing SSL env.

Ref: #290

* Properly close SSL socket in _loopback_for_cert

Fixes #290

* Apply suggestions from code review

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Silence PT016 in the value `pytest.fail()` call

* Fix the invocation syntax of `pytest.fail()`

Ref:
https://github.com/m-burst/flake8-pytest-style/issues/44#issuecomment-642481337

* Set the default role in Sphinx to "any"

* Resolve unclosed resourcewarning in pyopenssl

* Disable parallel mode for sphinxcontrib.spelling

They've declared in metadata that this extension does not
support parallel reads:
 * https://github.com/sphinx-contrib/spelling/pull/54
 * https://github.com/sphinx-contrib/spelling/issues/55

Based on above, and combined with '-j auto' + strict mode, Sphinx
now explodes unless we make it single-worker.

* 📝 Skip checking doc links to own issues and PRs

This may need to be revisited once Sphinx implements
https://github.com/sphinx-doc/sphinx/issues/7388

* Add new connection reset cases to TLS tests

* Allow nightly Python to fail in Travis CI

* Make in-tree Sphinx extensions importable

* Avoid ResourceWarning access under PyPy

* 🚑 xfail `test_keepalive[HTTP/1.1]` under PyPy

* Fix a few `test_tls_client_auth` cases @ AppVeyor

* Revert "Unxfail test_large_request"

This reverts commit 347b4d7f465b0c363ff330c1bc25d49665eb34be.

* xfail `test_large_request` under CircleCI

It's the only CI where it's reproducible in a stable manner.

* Set a brew install fallback in macOS @ CircleCI

* Update Pythons list under macOS @ CircleCI

* Add Python 3.8 to GNU/Linux jobs @ CircleCI

* Use Python 3.7.7 on macOS in CircleCI

Because 3.7.8 is not yet in pyenv shipped via brew

* Set the parallelism of 2 on Linux @ CircleCI

* Use Python 3.6.9 on macOS in CircleCI

Because 3.6.10 is not yet in pyenv shipped via brew

* Mark `test_large_request` as unstable

* xfail `test_keepalive[HTTP/1.1]` only under pypy3

* Xfail @ test_https_over_http_error under py2+win

* Mark `test_http_over_https_error` xfail unstable

* Mark test_https_over_http_error -> ConnectionError

* Drop Python 3.4 from macOS jobs @ CircleCI

* Be more graceful when terminating keep-alive connections. Ref #263.

The previous behaviour was that when we exceed our threshold of permitted
keep-alive connections, we would evict the least recently used connection
by forcibly shutting down the socket. This would cause problems with clients
which wouldn't be expecting socket errors.

Now, if we have a connection that we would usually keep-alive, but we have
already reached our limit of allowed keep-alive connections, then we close
the connection gracefully by sending a "Connection: Close" header for
HTTP/1.1 or omitting the "Connection" header for HTTP/1.0.

This has the downside of having cheroot holding on to connections which are
less recently used, rather than the most recent ones - but it does ensure that
we make the decision about whether to keep or drop a connection at the time we
are writing the headers, which allows the client to have a better expectation
about the state of the socket once the response has been read.

However, we still forcibly close sockets for idle keep-alive connections once
the server timeout has been exceeded.

* Drop an unused leftover arg from `cheroot.connections`

* Add a docstring to `can_add_keepalive_connection`

* Unxfail test_connection_keepalive

* Set server timeout to 20 in test_wsgi

* Experiment with disabling the expiration of keep-alive connections.

* Revert "Experiment with disabling the expiration of keep-alive connections."

This reverts commit 0bb15fc920aee150cbb7f2b15e1e8ab47cf79497.

* Make keepalive tests under macOS less stressful

* Add a note to the changelog

* Revert "Temporary limit pytest<5.4"

This reverts commit acdd75291acbeed261d915e786945ffd1b265fef.

* Bump pytest-sugar to v0.9.3

Ref: https://github.com/Teemu/pytest-sugar/pull/188#issuecomment-619550736

* Mention PRs #291 and #298 in changelog

* Add "unclosed" to the list of known words

* Bump GHA deps

* Make tox setup in GHA verbose

* Use Python 3.8 in Sphinx envs

* Use Python 3.8 for doc envs in Travis CI

* Add words from py38 memoryview to known words

* Upgrade add-trailing-comma to v2.0.1

Addresses https://github.com/asottile/add-trailing-comma/issues/99

* Ignore `cryptography==3.0` "deprecation warning"

Refs:
* https://github.com/pyca/cryptography/issues/5335
* https://github.com/pytest-dev/pytest/issues/7524

* Use Python 3.8 for linting jobs in Zuul CI

* Use pyenv for Python 3.8 in Zuul

* 🚑 Recover linkcheck-docs tox env ref in Zuul CI

* server: reproduce select() out of range error

* feedback: move imports, make finally robust

* feedback: don't change hard_limit when adjusting nofile resource

* feedback: add assertions to enforce we reach a file-descriptor over 1024

* make test_high_number_of_file_descriptors py27 compatible

* connections: replace select with selectors/selectors2

* only run test_high_number_of_file_descriptors on unix

* really only run test_high_number_of_file_descriptors on unix

* feedback: use closing contextmanager for socket

* Update cheroot/test/test_server.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Update cheroot/connections.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Update cheroot/connections.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Update cheroot/test/test_server.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Update cheroot/test/test_server.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Update cheroot/test/test_server.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Update cheroot/test/test_server.py

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* Apply suggestions from code review

Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>

* move selectors import to compat

* integrate feedback with tests, make work again

* Use `http_server` fixture in `test_high_number_of_file_descriptors`

* Improve `test_high_number_of_file_descriptors` docstring

* Add LGTM ignore comments to `_compat`

* Revert "Use `http_server` fixture in `test_high_number_of_file_descriptors`"

This reverts commit 7e0900c88f16fa4bab4baf85825ac3331cf911b9.

* Move high fd num test prerequisites to fixtures

* Fix marking `select()` as code in docstring

* Add "syscall" to the list of known words

* Only install pytest-forked where it's supported

* Apply updated add-trailing-comma edits

* Conditionally decorate test with forked mark

* Bump setup-python GHA to v2.1.1

* Add selectors34 fallback for py27 under 64-bit Win

This change addresses a bug in selectors2 (that is resolved in master
but is unreleased) with fd of the "long" type not being recognized as
"int". Here's the traceback it causes:

  Traceback (most recent call last):
    File "C:\projects\cheroot\cheroot\server.py", line 1788, in serve
      self.tick()
    File "C:\projects\cheroot\cheroot\server.py", line 2023, in tick
      conn = self.connections.get_conn(self.socket)
    File "C:\projects\cheroot\cheroot\connections.py", line 163, in get_conn
      self._selector.unregister(fno)
    File "c:\projects\cheroot\.tox\python\lib\site-packages\selectors2.py", line 249, in unregister
      key = super(SelectSelector, self).unregister(fileobj)
    File "c:\projects\cheroot\.tox\python\lib\site-packages\selectors2.py", line 155, in unregister
      key = self._fd_to_key.pop(self._fileobj_lookup(fileobj))
    File "c:\projects\cheroot\.tox\python\lib\site-packages\selectors2.py", line 127, in _fileobj_lookup
      return _fileobj_to_fd(fileobj)
    File "c:\projects\cheroot\.tox\python\lib\site-packages\selectors2.py", line 90, in _fileobj_to_fd
      raise ValueError("Invalid file object: {0!r}".format(fileobj))
  ValueError: Invalid file object: 916L

Refs:
  * https://github.com/sethmlarson/selectors2/pull/10
  * https://twitter.com/webKnjaZ/status/1285695028136992769
  * https://github.com/berkerpeksag/selectors34/blob/1.2.0/selectors34.py#L51
  * https://github.com/cherrypy/cheroot/pull/301#issuecomment-662127125

* Revert "Add selectors34 fallback for py27 under 64-bit Win"

This reverts commit e996f20e29838ff1f95b597ee459d48c98ea2f22.

Thanks to @sethmlarson who published `selectors==2.0.2` on PyPI
we no longer need a fallback to `selectors34`.

Ref: https://twitter.com/sethmlarson/status/1285706586514751489

* Revert "Bump setup-python GHA to v2.1.1"

This reverts commit 72252db0c4162d2186cc23940557b81bee78220d.

* Ignore broken pipe in TLS tests on macos

* Add a `:user:` role to Sphinx

* Add change notes for v8.4.0

Co-authored-by: Joel Rivera <rivera@joel.mx>
Co-authored-by: Sviatoslav Sydorenko <wk@sydorenko.org.ua>
Co-authored-by: RJ Seibert <richard.j.seibert@gmail.com>
Co-authored-by: RJ Seibert <alephnot0@gmail.com>
Co-authored-by: Malcolm Robert <github@mxii.ca>
Co-authored-by: Sviatoslav Sydorenko <wk.cvs.github@sydorenko.org.ua>
Co-authored-by: pyup-bot <github-bot@pyup.io>
Co-authored-by: Mohammed Naser <mnaser@vexxhost.com>
Co-authored-by: Dmitriy Rabotyagov <drabotyagov@vexxhost.com>
Co-authored-by: Jason R. Coombs <jaraco@jaraco.com>
Co-authored-by: Safihre <safihre@sabnzbd.org>
Co-authored-by: Allan Crooks <allan.crooks@yougov.com>
Co-authored-by: Tom Milligan <tom@reinfer.io>
Co-authored-by: Tom Milligan <tommilligan@users.noreply.github.com>